version: '3.8'

services:

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  migrator:
    build:
      context: .
      dockerfile: MigrationDockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - 4000
    depends_on:
      - db
#  phoenix2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      PORT: 4000
#      DB_NAME: ${POSTGRES_DB}
#      DB_USER: ${POSTGRES_USER}
#      DB_PASSWORD: ${POSTGRES_PASSWORD}
#      DB_HOST: db
#      DATABASE_URL: ${DATABASE_URL}
#      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
#    ports:
#      - 4003:4000
#    depends_on:
#      - db