version: '3.8'

secrets:
  POSTGRES_PASSWORD:
    file: ./postgres-secrets.POSTGRES_PASSWORD
  POSTGRES_USER:
    file: ./postgres-secrets.POSTGRES_USER
  POSTGRES_DB:
    file: ./postgres-secrets.POSTGRES_DB

services:

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "/run/secrets/POSTGRES_PASSWORD"
      POSTGRES_USER: "/run/secrets/POSTGRES_USER"
      POSTGRES_DB: "/run/secrets/POSTGRES_DB"
    ports:
      - 5432:5432
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      COOKIE: a_cookie
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4001:80