version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "react_test"
    ports:
      - 5432:5432
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      COOKIE: a_cookie
      BASIC_AUTH_USERNAME: username
      BASIC_AUTH_PASSWORD: password
      BASIC_AUTH_REALM: realm
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ClientDockerfile
    ports:
      - 4001:80