version: '3.8'

services:

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4002:4000
    environment:
      PORT: 4000
      COOKIE: a_cookie
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DATABASE_URL: "ecto://postgres:postgres@db/react_test"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_ADDRESS: "localhost:4002"
    ports:
      - 4001:80
