apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      run: client
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
        - name: client
          image: react_test_umbrella_client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    run: client
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  clusterIP: 10.96.0.239
  type: LoadBalancer
  selector:
    run: client