apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-config
  labels:
    app: phoenix
data:
  DB_NAME: react_test
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: postgres
  DATABASE_URL: "ecto://postgres:postgres@postgres/react_test"